# Generated by Django 2.0.5 on 2018-07-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='公司全称')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系方式')),
                ('synonym', models.BooleanField(default=False, verbose_name='同义词库')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='词条名')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Company', verbose_name='公司通名')),
            ],
        ),
    ]
