# Generated by Django 2.0.5 on 2018-07-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_auto_20180705_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='描述'),
        ),
    ]
