# Generated by Django 2.0.5 on 2018-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0008_auto_20180721_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='company',
            field=models.ManyToManyField(blank=True, to='annotate.Company', verbose_name='企业'),
        ),
        migrations.AlterField(
            model_name='news',
            name='finance',
            field=models.ManyToManyField(blank=True, to='annotate.Finance', verbose_name='投融资关系'),
        ),
    ]
