# Generated by Django 2.0.5 on 2018-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0009_auto_20180721_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tech',
            field=models.ManyToManyField(blank=True, to='annotate.Tech', verbose_name='技术关键词'),
        ),
    ]
