# Generated by Django 2.0.5 on 2018-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0010_auto_20180721_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordscompany',
            name='is_labeled',
            field=models.BooleanField(default=False, verbose_name='是否标注'),
        ),
        migrations.AddField(
            model_name='keywordstech',
            name='is_labeled',
            field=models.BooleanField(default=False, verbose_name='是否标注'),
        ),
    ]
